### PR TITLE
add a description for the module

### PR DESCRIPTION
**Pull request by RinkiyaKeDad**

### CODE REVIEW

**Comment by RinkiyaKeDad** [comment]
@jpadams do we need to push a new release as well for this to reflect? Also please review, thanks!

**Comment by jpadams** [comment]
> @jpadams do we need to push a new release as well for this to reflect? Also please review, thanks!

Yes, we would, but you can publish a dev version like this and see the results:
https://daggerverse.dev/mod/github.com/okteto/dagger-module@a8d1d2c11d907deac27fcd1243b773a39ab8f024

Looks good!

I'll send a PR after this one to improve the function comments.

**Review by jpadams — APPROVED** [review]
LGTM!

**Comment by RinkiyaKeDad** [comment]
>I'll send a PR after this one to improve the function comments. 

Thanks! I'll cut a release after you send that so that all the latest changes are there.

**Pull request merged**
